### PR TITLE
added null safety (see: https://dart.dev/null-safety)

### PR DESCRIPTION
**Pull request by GinoTerlouw**
I've made some minor changes that would make the package ready for the upcoming null safe releases of dart/flutter.

### CODE REVIEW

**Comment by christocracy** [comment]
Thanks!  Now do `flutter_background_geolocation` :)

**Comment by christocracy** [comment]
You've tested this?

**Comment by GinoTerlouw** [comment]
Yes, I did! it works on the example app. If merged I would love to do `flutter_background_geolocation` as well. Just make sure that if you happen to release a null safe version that it would need to be a pre release version since it doesn't work yet on 1.22.6 yet without adding some flags to flutter run.

**Comment by christocracy** [comment]
I had to merge an [important  PR](https://github.com/transistorsoft/flutter_background_fetch/pull/189) and release a new version yesterday.  I'll be looking into merging this next week (hopefully).

**Comment by GinoTerlouw** [comment]
alright, will update the merge request later today

**Comment by christocracy** [comment]
I'm working on fixing up conflicts on your PR currently.

**Comment by christocracy** [comment]
I resolved the conflicts in my branch [null-safety](https://github.com/transistorsoft/flutter_background_fetch/tree/null-safety)

Could you please test out that branch?

**Comment by christocracy** [comment]
Do you know how to solve this with `dartanalyzer`?

**Comment by GinoTerlouw** [comment]
either make sure to be in the beta channel `flutter channel beta && flutter upgrade` or add the following flag to your run command `--enable-experiment=non-nullable`

**Comment by GinoTerlouw** [comment]
or you could add the following to your analysis_options.yaml
```yml
analyzer:
  enable-experiment:
    - non-nullable
```

**Comment by christocracy** [comment]
>either make sure to be in the beta channel flutter channel beta && flutter upgrade

Yes, of course.  The code would fail were I not on beta channel.

Btw, when testing my branch `null-safety`, you'll need to be aware of the [**Breaking Changes** from `0.7.0`](https://github.com/transistorsoft/flutter_background_fetch/blob/null-safety/CHANGELOG.md#100-nullsafety0---2021-02-15).

>or you could add the following to your analysis_options.yaml

Yup, [tried that](https://github.com/transistorsoft/flutter_background_fetch/blob/null-safety/analysis_options.yaml#L2-L3)

**Comment by GinoTerlouw** [comment]
Not sure which IDE you are on, had the same problem with android studio did the steps above `flutter clean` and restarted the IDE which resolved the problem for me. I'll check your branch right now!

**Comment by GinoTerlouw** [comment]
Everything is working, and I do not get any of the null-safety warnings, perhaps there is a difference in our flutter version somehow?

```console
[√] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.26.0-17.5.pre at C:\flutter
    • Framework revision 1fe38dcb5f (5 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ginod\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\ginod\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

• No issues found!

```

**Comment by christocracy** [comment]
It's only `dartanalyzer` which has problems.  Android Studio doesn't recognize anything wrong and the */example* app builds fine.

```console
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-CA)
    • Flutter version 1.26.0-17.5.pre at /Volumes/Glyph2TB/Users/chris/development/flutter
    • Framework revision 1fe38dcb5f (5 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/Glyph2TB/Users/chris/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Volumes/Glyph2TB/Users/chris/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Volumes/Glyph2TB//Users/chris/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 12 Pro (mobile) • 0F28727E-1042-4E83-9AD9-DB3AA93B7623 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!
```

**Comment by christocracy** [comment]
>Everything is working

Let me know when it's good to merge and I'll go ahead and release `1.0.0-nullsaftety.0` to `pub.dev`.

**Comment by GinoTerlouw** [comment]
I think it's good to go! I'm using the branch already to make background-geolocation null-safe. There seem to be some (forgotten?) Packages you use in the example app which aren't and perhaps will not be null-safe - so if you agree on that - I will look for replacements on those

**Comment by christocracy** [comment]
>Packages you use in the example app which aren't and perhaps will not be null-safe

Go ahead.

You had no issues with the **Breaking Changes** noted in the CHANGELOG?

**Comment by GinoTerlouw** [comment]
As with your null-safety branch no

**Comment by christocracy** [comment]
Ok, this is now merged to master via https://github.com/transistorsoft/flutter_background_fetch/pull/190.

Your support here is *much* appreciated.  Do you have a license for `flutter_background_geolocation`?

**Comment by christocracy** [comment]
`1.0.0-nullsafety.0` is [now published](https://pub.dev/packages/background_fetch/versions/1.0.0-nullsafety.0)

**Comment by GinoTerlouw** [comment]
> Ok, this is now merged to master via #190.
> 
> Your support here is _much_ appreciated. Do you have a license for `flutter_background_geolocation`?

No problem! That is the least that I can do. No I do not, our app is still in a pre beta phase so we didn't buy the license yet since it isn't distributed via the play store yet. 

Null-safety on background geolocation will take some time, I'm looking for replacements for some packages since they aren't actively supported.

**Comment by christocracy** [comment]
>we didn't buy the license yet

Email me at `chris@transistorsoft.com` for a free license key.

**Comment by GinoTerlouw** [comment]
Hopefully this weekend I'll be done with null-safety on background geolocation, had some exams in the way.

**Comment by christocracy** [comment]
Good.

You’re a student?

**Comment by GinoTerlouw** [comment]
Yes, student and working in a 3 man startup.

**Pull request merged**
